version: '3'
services:
  pg-database:
    image: postgres:13
    container_name: pg-database
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ny_taxi
    volumes:
      - ny_taxi_postgres_data:/var/lib/postgresql/data
    ports:
      - 1111:5432
    networks:
      - pg-network

  taxi_ingest_data:
    image: taxi_ingest:v1
    container_name: taxi_ingest_data
    command: [
      "--port", "5432", 
      "--db", "postgres", 
      "--table", "green_taxi_data", 
      "--url", "https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2019-09.csv.gz",
      "--host", "pg-database"
    ]
    networks:
      - pg-network

  taxi_ingest_times:
    image: taxi_ingest:v1
    container_name: taxi_ingest_times
    command: [
      "--port", "5432", 
      "--db", "postgres", 
      "--table", "green_taxi_times", 
      "--url", "https://s3.amazonaws.com/nyc-tlc/misc/taxi+_zone_lookup.csv",
      "--host", "pg-database"
    ]
    networks:
      - pg-network

networks:
  pg-network:
    driver: bridge

volumes:
  ny_taxi_postgres_data:
    